---
version: '3.7'
networks:
  vnet:
    driver: bridge
services:
  # HomeAssistant
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    environment:
      - TZ
    volumes:
      - /home/${USER}/containers/home_assistant:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    deploy:
      replicas: 1
    ports:
      - "8123:8123"
